Enabling android back button.
fga-eps-mds/2018.2-FGAPP-FrontEnd pull request #123
Opened 2018-11-23 01:12 UTC by shayanealcantara

Co-authored-by: André Lucas de Sousa Pinto <andrelucax@gmail.com>
Co-authored-by: Shayane Alcantara <shayaneliebe@gmail.com>

## Descrição
O botão de voltar foi reabilitado entre as telas do app, exceto na tela de Login.

Soluciona issue fga-eps-mds/2018.2-Integra-Vendas/issues/301

---

- [x] Estou utilizando o ambiente configurado

2018-11-30 02:40 UTC, WelisonR reviewed
O botão de voltar está funcionando como deveria, porém não consegui realizar a criação de um produto, estou a receber o seguinte erro: `Invalid token specified`. Por favor, revise a questão do token.

2018-11-30 04:24 UTC, shayanealcantara commented
@WelisonR, corrigido :) Poderia revisar novamente?

2018-11-30 19:24 UTC, WelisonR requested changes
A aplicação continua apresentando problemas com o _token_. Na tela de perfil de usuário ao tentar trocar o nome do usuário, ocorre um erro com o _token_ (a _navigation_ está com parâmetros incorretos). Outro problema é no momento de marcar um pedido como atendido ou cancelá-lo, acaba apresentando na tela `Falha na autenticação` e o mesmo ocorre na tela de edição de produto. Por favor, corrigir os erros relacionados ao _token_.

2018-12-01 17:14 UTC, gustavolima00 commented
O problema foi resolvido, peço que avalie novamente @WelisonR

2018-12-01 22:31 UTC, WelisonR reviewed
@gustavolima00  @shayanealcantara 
A tela de editar produto continua com o problema de `Falha na autenticação`

2018-12-02 00:03 UTC, WelisonR approved these changes
Os critérios da issue foram satisfeitos. Não aparentando mais problemas, aceito esse _Pull Request_. Bom trabalho!

Observação: utilizou-se os microsserviços do _heroku_ para testar a aplicação.

2018-12-02 00:03 UTC, merged