Vendas app/style
fga-eps-mds/2018.2-FGAPP-FrontEnd pull request #33
Opened 2018-10-04 14:06 UTC by gustavolima00

## Pull Request
(FIX) fga-eps-mds/2018.2-iFood#109

Testado em branchs estáveis do backend. Caso a dev nao funcione mude todas as branches para feature/integration

2018-10-06 14:09 UTC, andrelucax requested changes
Na tela de meus pedidos:
   - Precos com valor maior que 10 reais quebra a linha separando R$ do preco.. Colocar na mesma linha

Cadastro de Meu Produto:
   - Teclado esta tampando o campo enquanto se digita.. Fazer subir o campo

2018-10-07 02:34 UTC, gustavolima00 commented
@andrelucax estou com dificuldades em fazer a tela subir ao selecionar campo.

2018-10-07 02:48 UTC, andrelucax commented
> @andrelucax estou com dificuldades em fazer a tela subir ao selecionar campo.

Vou tentar fzr a funcao, se eu conseguir vou commitar aqui

2018-10-07 21:06 UTC, andrelucax approved these changes
Vou aceitar o PR pois traz o mesmo valor do que ja' esta na dev com o layout correto e arrumaremos o q foi pedido em outra issue. bom trablho

2018-10-07 21:06 UTC, merged