fga-eps-mds/2018.2-IndicaAi#123 - View local
fga-eps-mds/2018.2-FGAPP-FrontEnd pull request #36
Opened 2018-10-08 00:45 UTC by heronsousa

2018-10-09 12:20 UTC, min-ia requested changes

2018-10-09 12:20 UTC, min-ia commented on mobile/screens/LoginScreen.js
> +      fetch('http://5babadabecc1a70014306b40.mockapi.io/api/rest-auth/login', {
Acredito que esta alteração é pra ficar somente no local de vocês.

2018-10-09 12:20 UTC, min-ia commented on mobile/screens/tab_navigator/indica_ai/IndicaAiApp.js
> -          <Provider store={store}>
A página inicial vai ser só o ViewLocal? Porque retiraram o código do SearchLocal daqui?

2018-10-09 12:20 UTC, min-ia commented on mobile/screens/tab_navigator/indica_ai/IndicaAiApp.js
> -          <Provider store={store}>
O certo seria vocês linkarem o componente Local que é renderizado como resultado da busca pra redirecionar pra ViewLocal

2018-10-09 12:20 UTC, min-ia commented on mobile/screens/tab_navigator/indica_ai/IndicaAiApp.js
> +  console.log(store.getState());
Os console.logs podem ser retirados. Servem somente pra debug.

2018-10-09 12:20 UTC, min-ia commented on mobile/screens/tab_navigator/indica_ai/containers/ViewLocal.js
> +            <Image style={{height: 230, width: 360}}
Essa altura e largura definida funciona com diferentes tamanhos de telas? E com outras imagens que não tenham essa proporção?

2018-10-09 12:20 UTC, min-ia commented on mobile/screens/tab_navigator/vendas/screens/Offers.js
> +    Screen provided to present the products already ordered by a certain user.
Porque vocês estão commitando arquivo do app de vendas?

2018-10-10 00:08 UTC, heronsousa commented on mobile/screens/tab_navigator/indica_ai/IndicaAiApp.js
> -          <Provider store={store}>
Sim, como você disse que não iriamos linkar agora essa página, estavamos usando ela na principal só para testar o código. Esqueci de reverter isso.

2018-10-10 01:09 UTC, min-ia approved these changes

2018-10-10 01:10 UTC, merged