Linking forgot password text
fga-eps-mds/2018.2-FGAPP-FrontEnd pull request #42
Opened 2018-10-11 01:29 UTC by gustavolima00

## Descrição
Criação de link na página inicial redirecionando para alteração de senha

**Issue do repositorio geral**
soluciona issue fga-eps-mds/2018.2-iFood#41

Tarefas gerais realizadas
* Criação do link no front end direcionando para redefinição de senha

2018-10-12 04:53 UTC, shayanealcantara requested changes
**Aparelho: Moto C Plus**
**Sistema operacional: Android: 7.0**

## Comportamento esperado: 
Ao clicar em "Esqueci minha senha", tenho que ser redirecionada a uma página web para inserir meu email de cadastro. Ao inserir o endereço de email, tenho que receber um link para a troca de senha no meu email. Ao clicar neste link, tenho que ser redirecionada para uma página web e trocar a senha.
 
## Comportamento atual:
Ao clicar em "Esqueci minha senha", sou redirecionada a uma página web para inserir meu email de cadastro. Ao inserir o endereço de email, recebi um link para a troca de senha no meu email. Ao clicar neste link, uma mensagem de erro aparece na tela. 
![index](https://user-images.githubusercontent.com/33501171/46848512-a75b6600-cdc0-11e8-8b68-1f1d943f1321.jpeg)


![index2](https://user-images.githubusercontent.com/33501171/46848503-9b6fa400-cdc0-11e8-906d-944ef87017c2.jpeg)

## Passos para reproduzir o comportamento atual:
- Clicar em "Esqueci minha senha";
- Digitar o endereço de email de cadastro;
- Ir ao email e clicar no link enviado para troca de senha;

## Adicional

**Sistema operacional: Ubuntu 18.04**

Fazendo o mesmo procedimento no navegador, o link enviado para a troca de senha é redirecionado para a página web sem erro, como ilustra as imagens a seguir. 
![screenshot from 2018-10-12 01-20-44](https://user-images.githubusercontent.com/33501171/46848622-55ffa680-cdc1-11e8-8a86-01c854f6e4ea.png)

![screenshot from 2018-10-12 01-21-09](https://user-images.githubusercontent.com/33501171/46848633-66b01c80-cdc1-11e8-877d-20a2b6dc93d7.png)

2018-10-13 12:25 UTC, andrelucax commented
@shayanealcantara 

O link que foi enviado para seu e-mail e o link default "localhost:8000" que existe no microservice de login.

Dentro do microservice de login existe um env-reference para criar um .env que ia enviar o email do jeito correto. Basta ir ao microservice de login, criar um .env no mesmo diretorio do env-reference e trocar pro seu IP la. Voce devera estar rodando o microservice de login do seu PC e o .env do front deve se referenciar ao eu PC.

2018-10-13 13:02 UTC, shayanealcantara commented
@andrelucax Okay, com esses dados que você colocou deu certo aqui. Logo, essa issue está sendo aceita. Bom trabalho!

2018-10-13 13:02 UTC, shayanealcantara approved these changes

2018-10-13 13:03 UTC, merged