Vendas app/order detail
fga-eps-mds/2018.2-FGAPP-FrontEnd pull request #47
Opened 2018-10-12 03:56 UTC by leomedeiros1

Co-authored-by: Shayane Alcantara <shayaneliebe@gmail.com>
Co-authored-by: Leonardo Medeiros <leonardomedeiros.6@gmail.com>

## Descrição

Adicionados nome do produto e nome do comprador aos detalhes de um pedido. Ajustada estilização de acordo com o protótipo.

Soluciona issue fga-eps-mds/2018.2-iFood#85

---
**Relacionado a:**
https://github.com/fga-eps-mds/2018.2-iFood/pull/192
https://github.com/fga-eps-mds/2018.2-FGAPP-login/pull/14
https://github.com/fga-eps-mds/2018.2-FGAPP-produto/pull/17

2018-10-12 07:32 UTC, lucasca73 commented
@shayanealcantara @leomedeiros1 

eu não sei se esses erros são de agora, mas no iOS esta dando esses erros.

Não tem como clicar no picker de quantidade e o botão de pedir não responde.

<img src="https://user-images.githubusercontent.com/4529055/46854415-22c81200-cdd7-11e8-810e-0f16efae7bf2.PNG" width=200/>

<img src="https://user-images.githubusercontent.com/4529055/46854416-22c81200-cdd7-11e8-9c3c-7fcb3041384e.PNG" width=200 />

<img src="https://user-images.githubusercontent.com/4529055/46854417-22c81200-cdd7-11e8-80a6-b9f808f74790.PNG" width=200 />

<img src="https://user-images.githubusercontent.com/4529055/46854420-22c81200-cdd7-11e8-8146-63d9449f984e.PNG" width=200 />

2018-10-12 07:42 UTC, lucasca73 commented
Parece que é um problema com o deploy do servidor de pedidos no heroku. 

```json
{
    "error": "Não foi possível se comunicar com o servidor."
}
```

Vou assegurar que ele ta funcionando

2018-10-12 16:32 UTC, shayanealcantara commented
Testei aqui com o Android 7.0 e aparentemente está funcionando. Provavelmente, seja alguma incompatibilidade de alguma biblioteca. 

![12](https://user-images.githubusercontent.com/33501171/46881823-0225a980-ce23-11e8-8f03-8f8cbf72586e.jpeg)

![13](https://user-images.githubusercontent.com/33501171/46881821-0225a980-ce23-11e8-89a1-7300b775c449.jpeg)

![14](https://user-images.githubusercontent.com/33501171/46881820-018d1300-ce23-11e8-95ff-f0f494f538fd.jpeg)

2018-10-26 02:40 UTC, andrelucax requested changes
Quando clico pra ver os detalhes do produto, em baixo da foto tem uma linha preta que nao existe no prototipo, por favor a remova.
![image](https://user-images.githubusercontent.com/42394759/47541315-38493b80-d8af-11e8-956e-1bb6ac04e366.png)

2018-10-26 04:34 UTC, leomedeiros1 commented
A barra preta foi removida, e agora está de acordo com o protótipo. @andrelucax

2018-10-27 14:40 UTC, andrelucax approved these changes

2018-10-27 14:41 UTC, andrelucax commented
Bom trabalho, agora a tela esta recebendo os dados corretos e seguindo o prototipo

2018-10-27 14:41 UTC, merged