Indica ai app/127 register local api
fga-eps-mds/2018.2-FGAPP-FrontEnd pull request #65
Opened 2018-10-29 01:53 UTC by heronsousa

Creating container with initial form to register local in the IndicaAi API and linking it to RegisterLocal.

2018-10-29 12:16 UTC, min-ia requested changes

2018-10-29 12:16 UTC, mendesiasmin commented on mobile/screens/tab_navigator/indica_ai/containers/RegisterLocal.js
> +        <View style={styles.localMap} elevation={5}>
A ideia do container é que o return dele seja o mais simples possível. O ideal é que tudo que esteja relacionado a estilo esteja em um componente, e você só chame o componente em questão aqui. Então, tenta tirar ao máximo todas as configurações dos estilos e deixar o código o mais reaproveitável possível.

2018-10-29 12:16 UTC, mendesiasmin commented on mobile/screens/tab_navigator/indica_ai/containers/RegisterLocalAPI.js
> +    return (
Aqui vale a mesma ideia de reaproveitar, o return deve ser simples e código deve estar mais reaproveitado possível, então, passar essa lógica para os componentes.

2018-10-29 12:16 UTC, mendesiasmin commented on mobile/screens/tab_navigator/indica_ai/containers/RegisterLocalAPI.js
> +          <Picker
Todo esse Picker pode ser um componente CategorySelect ou algo do tipo. Assim nós iremos conseguir usar a lógica para criar essa lista de categorias em outras partes do código.

2018-10-29 12:16 UTC, mendesiasmin commented on mobile/screens/tab_navigator/indica_ai/containers/RegisterLocalAPI.js
> +    return (
O legal é que você tivesse um componente do tipo RegisterAPIForm, assim se futuramente nós quisessemos criar uma página de editar o local, a gente só reaproveitaria o mesmo form que é usado no cadastro.

2018-10-29 13:45 UTC, heronsousa commented on mobile/screens/tab_navigator/indica_ai/containers/RegisterLocal.js
> +        <View style={styles.localMap} elevation={5}>
Essa parte já estava na devel, não mexi nela. Pelo o que eu entendi, esse style é só a formatação de como mapa será renderizado no container.

2018-10-31 21:57 UTC, min-ia approved these changes

2018-10-31 21:57 UTC, merged